settings:
  title: 'PDN Cloud Status'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: protv-local-streams # unique identifier
    name: Local Restream
    description: 'You write code. They handle the rest.' # default=empty
    url: 'http://local.protvmm.live:45153/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: protvmm.live
    name: Pro TV IPTV
    description: 'Pro TV IPTV'
    url: 'http://protvmm.live/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: tv.protvmm.live
    name: Pro TV Restream
    url: 'http://tv.protvmm.live:25461/'
    method: GET
    expectStatus: 302
